### ISSUE TITLE
Restful project endpoints

### ISSUE THREAD

**Issue by ajm188** [ajm188/fugl#17]
Issue for discussion on what I've been working on. Way I see it, we need the following endpoints (all of which require auth):

- [x] list projects owned by user
- [x] list projects shared with user
- [x] list projects owned or shared with user
- [x] show a single project
  - user must be able to view project
- [x] update a project
  - user must be able to edit project
- [x] update sharing settings on a project
  - user must be owner
- [x] delete a project
  - user must be owner

**Comment by ajm188** [comment]
@dealie16 if there's any other endpoints you think we'll need, give a shout. Otherwise, PR coming soon to a repo near you

**Comment by dealie16** [comment]
Endpoint to check if a username is taken. There may be some other form validation endpoints, but that is the first one I thought of.

**Comment by ajm188** [comment]
Moving this to another issue. Probably one issue per resource.

**Comment by ajm188** [comment]
Updated checklist as per #20
